add colors to some params update params generator

diff --git a/indatabase b/indatabase
--- a/indatabase
+++ b/indatabase
@@ -7,11 +7,33 @@ cd "$(dirname "$0")"
 # @author Jesus Alcaraz <jesus@gammapartners.com>
 THISOUTPUT="$(php 'mysql_connectors')"
 THISCONNECTOR=""
-echo "mysql ${THISCONNECTOR}"
+
 while read -r line; do
     #echo "... $line ..."
     THISCONNECTOR=$line
 done <<< "$THISOUTPUT"
-    echo "-- $THISCONNECTOR --"
-#exit
-mysql $THISCONNECTOR
+
+#exit \o/\W \r:\m \u [\]
+command -v mysql >/dev/null 2>&1 || { echo >&2 "I require mysql but it's not installed.  Aborting."; exit 1; }
+#if hash altsql 2>/dev/null; then
+#	echo "
+#	 altsql ${THISCONNECTOR} 
+#	 ";
+#    altsql $THISCONNECTOR;
+#    exit 0;
+#fi
+if hash rlwrap 2>/dev/null; then
+	echo "
+	rlwrap -a -p'RED' --prompt-colour='1;34' mysql -A ${THISCONNECTOR} --prompt=\"\\o/\\w \r:\\m\\P \\u[\\d]>\\_ \n\"
+	";
+    rlwrap -a -p'RED' --prompt-colour='1;34'  mysql -A $THISCONNECTOR  --prompt="\\o/\\w \r:\\m\\P \\u[\\d]>\\_";
+    exit 0;
+fi
+
+echo " 
+    mysql ${THISCONNECTOR} --prompt=\"\\o/\\w \r:\\m\\P \\u[\\d]>\\_ \n\"
+";
+mysql $THISCONNECTOR  --prompt="\\o/\\w \r:\\m\\P \\u[\\d]>\\_";
+exit 0;
+
+
